const fs = require('fs');
const path = require('path');
const os = require('os');

const platform = os.platform();
const moduleName = 'Milky2018/mgstudio';
const engineRoot = __dirname;
const generatedWgslFilePath = path.join(
  engineRoot,
  'naga_oil',
  'wgsl_embedded.generated.mbt',
);

function toPosixRelative(filePath) {
  return path.relative(engineRoot, filePath).split(path.sep).join('/');
}

function collectWgslFilesInDir(dirPath, out) {
  if (!fs.existsSync(dirPath)) {
    return;
  }
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    const entryPath = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      collectWgslFilesInDir(entryPath, out);
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.wgsl')) {
      out.push(entryPath);
    }
  }
}

function writeFileIfChanged(filePath, content) {
  const prev = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : '';
  if (prev === content) {
    return;
  }
  fs.writeFileSync(filePath, content, 'utf8');
}

function generateEmbeddedWgslRegistry() {
  const roots = [
    'anti_alias',
    'assets',
    'core_pipeline',
    'pbr',
    'post_process',
    'render',
    'sprite_render',
    'ui_render',
  ].map((rel) => path.join(engineRoot, rel));
  const wgslFiles = [];
  for (const root of roots) {
    collectWgslFilesInDir(root, wgslFiles);
  }
  wgslFiles.sort((lhs, rhs) => toPosixRelative(lhs).localeCompare(toPosixRelative(rhs)));
  const lines = [
    '// This file is auto-generated by build.js.',
    '// Do not edit manually.',
    '',
    '///|',
    'fn register_generated_embedded_wgsl_sources() -> Unit {',
  ];
  for (const filePath of wgslFiles) {
    const relPath = toPosixRelative(filePath);
    const source = fs.readFileSync(filePath, 'utf8');
    lines.push(`  register_wgsl_source(${JSON.stringify(relPath)}, ${JSON.stringify(source)})`);
  }
  lines.push('}');
  lines.push('');
  writeFileIfChanged(generatedWgslFilePath, lines.join('\n'));
}

function pkg(path) {
  return `${moduleName}/${path}`;
}

generateEmbeddedWgslRegistry();

const linkConfigs = [];

function addLinkConfig(packageName, linkFlags) {
  linkConfigs.push({
    package: packageName,
    link_flags: linkFlags,
  });
}

if (platform === 'darwin' || platform === 'linux') {
  const zlibLinkFlags = '-lz';
  const zlibLinkedPackages = [pkg('asset'), pkg('ui'), pkg('shader'), pkg('audio')];
  for (const packageName of zlibLinkedPackages) {
    addLinkConfig(packageName, zlibLinkFlags);
  }
}

if (platform === 'darwin') {
  const darwinWindowLinkFlags =
    '-framework AppKit -framework QuartzCore -framework Foundation -lobjc -Wl,-undefined,dynamic_lookup';

  addLinkConfig(pkg('window/windowing_native'), darwinWindowLinkFlags);
}

console.log(
  JSON.stringify({
    link_configs: linkConfigs,
  }),
);
